# Generated by Django 2.2.6 on 2019-10-27 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=255)),
                ('confirmations', models.IntegerField()),
                ('size', models.IntegerField()),
                ('height', models.IntegerField()),
                ('version', models.IntegerField()),
                ('pow_algo_id', models.IntegerField()),
                ('pow_algos', models.CharField(max_length=255)),
                ('pow_hash', models.CharField(max_length=255)),
                ('merkleroot', models.CharField(max_length=255)),
                ('time', models.IntegerField()),
                ('nonce', models.IntegerField()),
                ('bits', models.CharField(max_length=255)),
                ('difficulty', models.FloatField()),
                ('chainwork', models.CharField(max_length=255)),
                ('previousblockhash', models.CharField(max_length=255)),
                ('nextblockhash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=255)),
                ('version', models.IntegerField()),
                ('locktime', models.IntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Block')),
            ],
        ),
        migrations.CreateModel(
            name='Vout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('n', models.IntegerField()),
                ('asm', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('hex', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('reqSigs', models.IntegerField(blank=True, default=None, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('txid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Vin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vout', models.IntegerField()),
                ('asm', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('hex', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('sequence', models.IntegerField(blank=True, default=None, null=True)),
                ('coinbase', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('txid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('vout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Vout')),
            ],
        ),
    ]
