# Generated by Django 2.2.6 on 2019-10-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='pow_algos',
            new_name='pow_algo',
        ),
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
