# Generated by Django 2.2.6 on 2019-10-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_auto_20191027_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vin',
            old_name='txid',
            new_name='tx',
        ),
    ]
