# Generated by Django 2.2.6 on 2019-10-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_auto_20191027_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vin',
            name='vout',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
