# Generated by Django 2.2.6 on 2019-10-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0004_auto_20191027_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vin',
            name='sequence',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
