# Generated by Django 2.2.6 on 2019-10-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0005_auto_20191027_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vout',
            old_name='txid',
            new_name='tx',
        ),
    ]
