# Generated by Django 2.2.6 on 2019-10-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0006_auto_20191027_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='confirmations',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='block',
            name='nonce',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='block',
            name='time',
            field=models.BigIntegerField(),
        ),
    ]
