# Generated by Django 2.2.6 on 2019-10-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0007_auto_20191027_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='vin',
            name='scriptpubkey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vin',
            name='scriptsig',
            field=models.BooleanField(default=False),
        ),
    ]
