# Generated by Django 2.2.6 on 2019-10-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0008_auto_20191027_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='bits',
            field=models.CharField(max_length=1255),
        ),
        migrations.AlterField(
            model_name='block',
            name='chainwork',
            field=models.CharField(max_length=1255),
        ),
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(max_length=1255, unique=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='merkleroot',
            field=models.CharField(max_length=1255),
        ),
        migrations.AlterField(
            model_name='block',
            name='nextblockhash',
            field=models.CharField(max_length=1255),
        ),
        migrations.AlterField(
            model_name='block',
            name='pow_algo',
            field=models.CharField(max_length=1255),
        ),
        migrations.AlterField(
            model_name='block',
            name='pow_hash',
            field=models.CharField(max_length=1255),
        ),
        migrations.AlterField(
            model_name='block',
            name='previousblockhash',
            field=models.CharField(max_length=1255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txid',
            field=models.CharField(max_length=1255),
        ),
        migrations.AlterField(
            model_name='vin',
            name='asm',
            field=models.CharField(blank=True, default=None, max_length=1255, null=True),
        ),
        migrations.AlterField(
            model_name='vin',
            name='coinbase',
            field=models.CharField(blank=True, default=None, max_length=1255, null=True),
        ),
        migrations.AlterField(
            model_name='vin',
            name='hex',
            field=models.CharField(blank=True, default=None, max_length=1255, null=True),
        ),
        migrations.AlterField(
            model_name='vout',
            name='asm',
            field=models.CharField(blank=True, default=None, max_length=1255, null=True),
        ),
        migrations.AlterField(
            model_name='vout',
            name='hex',
            field=models.CharField(blank=True, default=None, max_length=1255, null=True),
        ),
        migrations.AlterField(
            model_name='vout',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=1255, null=True),
        ),
    ]
