# Generated by Django 2.2.6 on 2019-10-27 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('block', '0009_auto_20191027_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesting', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, default=None, max_length=1255, null=True)),
                ('posted', models.BooleanField(default=False)),
                ('vout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Vout')),
            ],
        ),
    ]
